"use client";
/** Whole-product local backup/export and validated rollback-safe restore UI. */
import { useRef,useState } from "react";
import { Download,FileUp,ShieldCheck } from "lucide-react";
import { AUTHORITATIVE_KEYS,createBackup,parseBackup,restoreBackup } from "../lib/backup";

export default function DataRecoveryPanel(){const input=useRef<HTMLInputElement|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
 const exportAll=()=>{setError("");const text=JSON.stringify(createBackup(localStorage),null,2),blob=new Blob([text],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`kaizen-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);setMessage("Backup exported.")};
 const importAll=async(file:File)=>{setError("");setMessage("");try{if(file.size>25_000_000)throw new Error("Backup file is too large");const backup=parseBackup(await file.text());if(!confirm(`Restore Kaizen backup from ${new Date(backup.exportedAt).toLocaleString()}? Current browser data will be replaced.`))return;restoreBackup(localStorage,backup);setMessage("Restore complete. Reloading Kaizen…");window.setTimeout(()=>window.location.reload(),250)}catch(caught){setError(caught instanceof Error?caught.message:"Restore failed")}};
 return <div className="p-4 overflow-y-auto max-h-[calc(100vh-205px)]"><div className="flex gap-3"><ShieldCheck className="text-emerald-300"/><div><h3 className="font-semibold">Local data recovery</h3><p className="text-[10px] text-gray-400 mt-1">Exports every authoritative browser key. AI sessions, provider overrides and evaluation data are never included.</p></div></div><div className="grid grid-cols-2 gap-2 mt-4"><button onClick={exportAll} className="setting-btn justify-center"><Download size={13}/>EXPORT BACKUP</button><button onClick={()=>input.current?.click()} className="setting-btn justify-center"><FileUp size={13}/>RESTORE BACKUP</button><input ref={input} type="file" accept="application/json,.json" className="hidden" onChange={event=>{const file=event.target.files?.[0];if(file)void importAll(file);event.target.value=""}}/></div><p className="text-[10px] text-gray-500 mt-4">{AUTHORITATIVE_KEYS.length} state keys · strict version, key, JSON, size and unsafe-object validation · rollback on storage failure.</p>{message&&<div className="mt-3 text-xs text-emerald-300">{message}</div>}{error&&<div role="alert" className="mt-3 text-xs text-red-300">{error}</div>}<style jsx>{`.setting-btn{display:flex;align-items:center;gap:6px;border:1px solid var(--n-line,rgba(148,163,184,.25));border-radius:8px;padding:9px;font-size:9px;color:inherit}`}</style></div>}
