/** Fixed server route for route requests. */
import { NextRequest, NextResponse } from "next/server";

export const dynamic="force-dynamic";
const MAX_BODY=1_000_000;
function sameHost(origin:string|null,host:string|null){if(!origin)return true;if(!host)return false;try{return new URL(origin).host===host}catch{return false}}
function gateway():URL{const url=new URL(process.env.KAIZEN_AI_GATEWAY_URL||"http://127.0.0.1:4317");const host=url.hostname.replace(/^\[|\]$/g,"");if(url.protocol!=="http:"||!["127.0.0.1","localhost","::1"].includes(host))throw new Error("KAIZEN_AI_GATEWAY_URL must be loopback HTTP");return url}
async function proxy(request:NextRequest,{params}:{params:Promise<{path:string[]}>}){const {path}=await params,target=gateway();target.pathname=`/${path.map(encodeURIComponent).join("/")}`;target.search=request.nextUrl.search;const headers=new Headers(),forwardedHost=request.headers.get("x-forwarded-host")||request.headers.get("host"),incomingOrigin=request.headers.get("origin");if(!sameHost(incomingOrigin,forwardedHost))return NextResponse.json({error:{code:"ORIGIN_DENIED",message:"Cross-site AI proxy request denied.",retryable:false}},{status:403});const engineOrigin=process.env.KAIZEN_AI_PROXY_ORIGIN||"http://localhost:3000";headers.set("origin",engineOrigin);for(const name of ["authorization","content-type","x-kaizen-pairing-code"]) {const value=request.headers.get(name);if(value)headers.set(name,value)}let body:ArrayBuffer|undefined;if(!["GET","HEAD"].includes(request.method)){const declared=Number(request.headers.get("content-length")||0);if(declared>MAX_BODY)return NextResponse.json({error:{code:"BODY_TOO_LARGE",message:"Request body is too large.",retryable:false}},{status:413});body=await request.arrayBuffer();if(body.byteLength>MAX_BODY)return NextResponse.json({error:{code:"BODY_TOO_LARGE",message:"Request body is too large.",retryable:false}},{status:413})}try{const upstream=await fetch(target,{method:request.method,headers,body,cache:"no-store",signal:request.signal});const responseHeaders=new Headers();for(const name of ["content-type","cache-control","x-content-type-options"]) {const value=upstream.headers.get(name);if(value)responseHeaders.set(name,value)}responseHeaders.set("cache-control","no-store");return new Response(upstream.body,{status:upstream.status,headers:responseHeaders})}catch{return NextResponse.json({error:{code:"ENGINE_OFFLINE",message:"Kaizen Intelligence is offline. Start the local engine and try again.",retryable:true}},{status:503,headers:{"cache-control":"no-store"}})}}
export const GET=proxy;export const POST=proxy;export const DELETE=proxy;export const OPTIONS=proxy;
