/** Regression gate for qa entertainment reports contracts. */
import assert from "node:assert/strict";
import type { EntertainmentEvent,EntertainmentItem } from "../lib/entertainmentTypes";
import { buildEntertainmentReport } from "../lib/entertainmentReports";
let passed=0;const test=(name:string,fn:()=>void)=>{fn();passed++;console.log(`  ✓ ${name}`)};
const item=(id:string,p:Partial<EntertainmentItem>):EntertainmentItem=>({id,type:"movie",title:id,genres:[],creators:[],cast:[],studios:[],countries:[],status:"planned",progress:{},repeats:0,priority:"medium",queueOrder:1,tags:[],favorite:false,archived:false,createdAt:new Date("2025-01-01").getTime(),updatedAt:new Date("2025-01-01").getTime(),...p});
const items=[item("film",{status:"completed",completedAt:"2025-02-10",rating:8,minutesConsumed:120,purchasePrice:400,genres:["Drama"],creators:["Director A"],tags:["dark"],releaseYear:1995,countries:["India"]}),item("book",{type:"book",status:"completed",completedAt:"2025-02-20",rating:10,minutesConsumed:480,purchasePrice:600,genres:["Drama","Sci-Fi"],creators:["Author B"],tags:["thoughtful"],releaseYear:2020}),item("drop",{status:"dropped",droppedReason:"Too slow"}),item("queue",{status:"planned",createdAt:new Date("2024-01-01").getTime()})];
const events:EntertainmentEvent[]=[{id:"e",itemId:"film",type:"completed",at:new Date("2025-02-10").getTime()}];const r=buildEntertainmentReport(items,events,2025);
console.log("\n── Entertainment report algorithms ──");
test("total count and minutes",()=>{assert.equal(r.totalCount,2);assert.equal(r.totalMinutes,600)});
test("rating average and histogram",()=>{assert.equal(r.averageRating,9);assert.equal(r.histogram[7].value,1);assert.equal(r.histogram[9].value,1)});
test("genre count and average",()=>{assert.equal(r.genreCounts[0].label,"Drama");assert.equal(r.genreCounts[0].value,2);assert.equal(r.genreRatings.find(x=>x.label==="Drama")?.value,9)});
test("creator ranking",()=>assert.equal(r.creatorRatings.length,2));
test("decade breakdown",()=>assert.deepEqual(r.decadeRatings.map(x=>x.label).sort(),["1990s","2020s"]));
test("monthly rollup",()=>{assert.equal(r.monthly[0].count,2);assert.equal(r.monthly[0].hours,10);assert.equal(r.monthly[0].avgRating,9)});
test("completion rate",()=>assert.ok(Math.abs(r.completionRate-66.666)<.1));
test("backlog age and abandonment",()=>{assert.ok(r.backlog[0].ageDays>365);assert.equal(r.abandoned[0].label,"Too slow")});
test("cost and cost per hour",()=>{assert.equal(r.totalCost,1000);assert.equal(r.costPerHour,100)});
test("year review",()=>{assert.equal(r.yearReview.count,2);assert.equal(r.yearReview.topRated[0].id,"book")});
test("activity heat includes event",()=>assert.equal(r.heat.get("2025-02-10"),1));
console.log(`\n${passed} report tests passed.`);
