"use client";
/** AFTERGLOW interface for entertainment stats workflows. */
import { useMemo, useState } from "react";
import { BarChart3, CalendarDays, Clock3, Coins, Flame, Gauge, Star, Trophy } from "lucide-react";
import type { EntertainmentState } from "../../lib/entertainmentTypes";
import { buildEntertainmentReport, type CountValue } from "../../lib/entertainmentReports";

export default function EntertainmentStats({state}:{state:EntertainmentState}){
 const years=Array.from(new Set(state.items.map(i=>Number((i.completedAt??"").slice(0,4))).filter(Boolean))).sort((a,b)=>b-a),[year,setYear]=useState(years[0]??new Date().getFullYear()),r=useMemo(()=>buildEntertainmentReport(state.items,state.events,year),[state.items,state.events,year]);
 return <div className="space-y-6"><section className="ent-panel rounded-[28px] p-6 md:p-8 relative overflow-hidden"><div className="absolute right-0 top-0 w-72 h-72 bg-fuchsia-500/10 rounded-full blur-3xl"/><div className="relative"><div className="text-xs tracking-[.26em] text-fuchsia-400">THE NUMBERS AFTER THE CREDITS</div><h1 className="text-3xl md:text-4xl font-black mt-2">Stats & year in review</h1><p className="text-sm mt-2" style={{color:"var(--muted)"}}>Every chart is calculated locally from your private archive.</p></div></section>
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><Kpi icon={<Trophy/>} label="Consumed" value={r.totalCount}/><Kpi icon={<Clock3/>} label="Time inside" value={`${(r.totalMinutes/60).toFixed(0)}h`}/><Kpi icon={<Star/>} label="Average rating" value={r.averageRating?r.averageRating.toFixed(1):"—"}/><Kpi icon={<Gauge/>} label="Completion rate" value={`${r.completionRate.toFixed(0)}%`}/></div>
 <div className="grid xl:grid-cols-2 gap-5"><Panel title="Consumption by medium" sub="Completed titles"><Bars values={r.byType}/></Panel><Panel title="Rating distribution" sub="All rated titles"><Histogram values={r.histogram}/></Panel></div>
 <Panel title="Activity heatmap" sub="Last 365 days · progress, episode, reading and status events"><Heatmap heat={r.heat}/></Panel>
 <div className="grid xl:grid-cols-3 gap-5"><Panel title="Top genres" sub="Completed-title count"><Bars values={r.genreCounts.slice(0,8)}/></Panel><Panel title="Rating by genre" sub="Average personal score"><ScoreList values={r.genreRatings.slice(0,8)}/></Panel><Panel title="Mood breakdown" sub="Tags on completed titles"><Bars values={r.moodCounts.slice(0,8)}/></Panel></div>
 <div className="grid xl:grid-cols-2 gap-5"><Panel title="Creator ranking" sub="Average rating · completed works"><ScoreList values={r.creatorRatings.slice(0,10)} showCount/></Panel><Panel title="Decade taste" sub="Average rating by release decade"><ScoreList values={r.decadeRatings}/></Panel></div>
 <div className="grid xl:grid-cols-[1.4fr_1fr] gap-5"><Panel title="Monthly consumption" sub="Count, time and satisfaction"><Monthly data={r.monthly.slice(-12)}/></Panel><Panel title="Satisfaction over time" sub="Monthly average rating"><Line data={r.satisfaction.slice(-18)}/></Panel></div>
 <div className="grid xl:grid-cols-3 gap-5"><Panel title="Backlog age" sub="Oldest Plan-to titles"><div className="space-y-2">{r.backlog.slice(0,8).map(i=><div key={i.id} className="flex text-xs"><span className="truncate">{i.title}</span><strong className={`ml-auto ${i.ageDays>365?"text-red-300":i.ageDays>90?"text-amber-300":""}`}>{i.ageDays}d</strong></div>)}{!r.backlog.length&&<Muted>No active backlog.</Muted>}</div></Panel><Panel title="Abandoned analysis" sub="Why titles were dropped"><Bars values={r.abandoned}/></Panel><Panel title="Cost analysis" sub="Logged purchase prices"><div className="text-4xl font-black text-emerald-300">₹{r.totalCost.toFixed(0)}</div><div className="text-sm mt-2" style={{color:"var(--muted)"}}>₹{r.costPerHour.toFixed(2)} per consumed hour</div><div className="h-2 bg-white/5 rounded-full mt-5"><div className="h-full bg-emerald-400 rounded-full" style={{width:`${Math.min(100,r.totalCost/100)}%`}}/></div></Panel></div>
 <Panel title="Year in review" sub="Annual completion summary"><div className="flex flex-wrap gap-2 mb-5">{(years.length?years:[year]).map(y=><button key={y} onClick={()=>setYear(y)} className={`px-3 py-1.5 rounded-full text-xs ${year===y?"bg-fuchsia-500 text-white":"bg-white/5"}`}>{y}</button>)}</div><div className="grid md:grid-cols-3 gap-4"><div><div className="text-[9px]" style={{color:"var(--muted)"}}>COMPLETED</div><div className="text-3xl font-black">{r.yearReview.count}</div></div><div><div className="text-[9px]" style={{color:"var(--muted)"}}>TIME</div><div className="text-3xl font-black">{(r.yearReview.minutes/60).toFixed(0)}h</div></div><div><div className="text-[9px]" style={{color:"var(--muted)"}}>TOP GENRE</div><div className="text-xl font-black">{r.yearReview.topGenres[0]?.label??"—"}</div></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-2 mt-5">{r.yearReview.topRated.map(i=><div key={i.id} className="rounded-xl border p-3" style={{borderColor:"var(--line)"}}><div className="text-xs font-bold truncate">{i.title}</div><div className="text-amber-300 text-[10px] mt-1">★ {i.rating}/10</div></div>)}</div></Panel>
 <Panel title="Consumption timeline" sub="Most recently completed"><div className="space-y-1">{r.timeline.slice(0,20).map(i=><div key={i.id} className="flex items-center border-b py-2 text-xs last:border-0" style={{borderColor:"var(--line)"}}><span className="w-20" style={{color:"var(--muted)"}}>{i.completedAt??"Unknown"}</span><strong className="truncate">{i.title}</strong><span className="ml-auto text-amber-300">{i.rating?`★ ${i.rating}`:""}</span></div>)}</div></Panel>
 </div>
}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="ent-panel rounded-2xl p-4"><div className="flex items-center gap-2 text-fuchsia-300 [&>svg]:w-4">{icon}<span className="text-[9px] tracking-wider" style={{color:"var(--muted)"}}>{label.toUpperCase()}</span></div><div className="text-2xl font-black mt-2">{value}</div></div>}
function Panel({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="ent-panel rounded-2xl p-5"><h2 className="font-black">{title}</h2><p className="text-[10px] mt-1 mb-4" style={{color:"var(--muted)"}}>{sub}</p>{children}</section>}
function Bars({values}:{values:CountValue[]}){const max=Math.max(1,...values.map(v=>v.value));return <div className="space-y-2">{values.map(v=><div key={v.label} className="grid grid-cols-[100px_1fr_30px] gap-2 items-center text-[10px]"><span className="truncate">{v.label}</span><div className="h-2 bg-white/5 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-fuchsia-500 to-cyan-300" style={{width:`${v.value/max*100}%`}}/></div><strong className="text-right">{v.value}</strong></div>)}{!values.length&&<Muted>No data yet.</Muted>}</div>}
function Histogram({values}:{values:CountValue[]}){const max=Math.max(1,...values.map(v=>v.value));return <div className="h-36 flex gap-2 items-end">{values.map(v=><div key={v.label} className="flex-1 text-center"><div className="bg-amber-400/80 rounded-t min-h-[2px]" style={{height:`${v.value/max*110}px`}} title={`${v.value} ratings`}/><div className="text-[9px] mt-2" style={{color:"var(--muted)"}}>{v.label}</div></div>)}</div>}
function ScoreList({values,showCount=false}:{values:{label:string;value:number;count?:number}[];showCount?:boolean}){return <div className="space-y-2">{values.map(v=><div key={v.label} className="flex text-xs"><span className="truncate">{v.label}</span>{showCount&&<span className="ml-2 text-[9px]" style={{color:"var(--muted)"}}>({v.count})</span>}<strong className="ml-auto text-amber-300">{v.value.toFixed(1)}</strong></div>)}{!values.length&&<Muted>No rated completions.</Muted>}</div>}
function Monthly({data}:{data:{month:string;count:number;hours:number;avgRating:number}[]}){const max=Math.max(1,...data.map(x=>x.count));return <div className="h-44 flex gap-2 items-end">{data.map(x=><div key={x.month} className="flex-1 min-w-5 text-center"><div className="bg-cyan-400/70 rounded-t" style={{height:`${Math.max(3,x.count/max*120)}px`}} title={`${x.count} titles · ${x.hours.toFixed(1)}h · ${x.avgRating.toFixed(1)}/10`}/><div className="text-[8px] mt-2 -rotate-45 origin-top-left whitespace-nowrap" style={{color:"var(--muted)"}}>{x.month}</div></div>)}</div>}
function Line({data}:{data:{month:string;value:number}[]}){if(data.length<2)return <Muted>Complete and rate titles across multiple months.</Muted>;const w=500,h=140,pts=data.map((x,i)=>`${i/(data.length-1)*w},${h-(x.value/10*h)}`).join(" ");return <svg viewBox={`0 0 ${w} ${h}`} className="w-full h-40"><defs><linearGradient id="sat" x1="0" x2="1"><stop stopColor="#ec4899"/><stop offset="1" stopColor="#22d3ee"/></linearGradient></defs>{[2,4,6,8,10].map(n=><line key={n} x1="0" x2={w} y1={h-n/10*h} y2={h-n/10*h} stroke="currentColor" opacity=".08"/>)}<polyline points={pts} fill="none" stroke="url(#sat)" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function Heatmap({heat}:{heat:Map<string,number>}){const today=new Date(),cells=Array.from({length:365},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()-(364-i));const iso=d.toISOString().slice(0,10),n=heat.get(iso)??0;return{iso,n}}),max=Math.max(1,...cells.map(x=>x.n));return <div className="grid grid-rows-7 grid-flow-col gap-[3px] overflow-x-auto pb-2">{cells.map(x=><div key={x.iso} title={`${x.iso}: ${x.n} actions`} className="w-3 h-3 rounded-[2px]" style={{background:x.n?`rgba(236,72,153,${.2+.8*x.n/max})`:"rgba(255,255,255,.05)"}}/>)}</div>}
function Muted({children}:{children:React.ReactNode}){return <p className="text-xs" style={{color:"var(--muted)"}}>{children}</p>}
