"use client";
import { useMemo, useState } from "react";
import { Compass, Dices, Film, Gauge, GitBranch, Sparkles, Target, Users } from "lucide-react";
import type { EntertainmentItem } from "../../lib/entertainmentTypes";
import { blindSpots, creatorMarathons, explorationScore, franchiseGaps, moodOptions, moodPick, recommendations, surprisePick } from "../../lib/entertainmentAnalytics";

export default function EntertainmentIntelligence({items,onOpen}:{items:EntertainmentItem[];onOpen:(id:string)=>void}){
 const recs=useMemo(()=>recommendations(items),[items]),moods=useMemo(()=>moodOptions(items),[items]),explore=useMemo(()=>explorationScore(items),[items]),blind=useMemo(()=>blindSpots(items),[items]),gaps=useMemo(()=>franchiseGaps(items),[items]),marathons=useMemo(()=>creatorMarathons(items),[items]);const [mood,setMood]=useState(moods[0]??""),[pick,setPick]=useState<EntertainmentItem|undefined>(),[creator,setCreator]=useState("");const marathon=marathons.find(x=>x.name===creator)??marathons[0];
 return <section className="space-y-6 mb-10"><div className="ent-panel rounded-[28px] p-6 md:p-8 relative overflow-hidden"><div className="absolute right-0 top-0 w-64 h-64 rounded-full bg-fuchsia-500/10 blur-3xl"/><div className="relative grid lg:grid-cols-[1fr_240px] gap-6 items-center"><div><div className="text-xs tracking-[.25em] text-fuchsia-400">LOCAL INTELLIGENCE</div><h2 className="text-2xl md:text-3xl font-black mt-2">Your taste, without surveillance.</h2><p className="text-sm mt-2" style={{color:"var(--muted)"}}>Recommendations and breadth scores run entirely against your private local library.</p></div><div className="rounded-2xl border p-4" style={{borderColor:"var(--line)"}}><div className="flex items-center"><Gauge className="text-cyan-300" size={18}/><span className="ml-2 text-xs font-black">EXPLORATION SCORE</span><strong className="ml-auto text-3xl text-cyan-300">{explore.score}</strong></div><div className="h-2 bg-white/5 rounded-full mt-3 overflow-hidden"><div className="h-full bg-gradient-to-r from-fuchsia-500 to-cyan-300" style={{width:`${explore.score}%`}}/></div><div className="grid grid-cols-5 gap-1 mt-3 text-center text-[8px]" style={{color:"var(--muted)"}}><span>{explore.genres}<br/>genres</span><span>{explore.creators}<br/>voices</span><span>{explore.decades}<br/>decades</span><span>{explore.countries}<br/>lands</span><span>{explore.types}<br/>types</span></div></div></div></div>
 <div><Title icon={<Sparkles size={14}/>} title="If you liked…" sub="Scored from your 8+/favorites against the Plan-to queue"/><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3">{recs.map(r=><button key={r.item.id} onClick={()=>onOpen(r.item.id)} className="ent-panel rounded-2xl p-4 text-left hover:-translate-y-0.5 transition"><div className="text-[9px] text-fuchsia-400">MATCH {r.score}</div><div className="font-black mt-1">{r.item.title}</div><p className="text-[10px] mt-2 line-clamp-2" style={{color:"var(--muted)"}}>{r.reasons.join(" · ")}</p><p className="text-[9px] mt-2 text-cyan-300 truncate">Because: {r.because.join(", ")}</p></button>)}{!recs.length&&<Empty text="Rate or favorite more titles and add tagged items to your queue."/>}</div></div>
 <div className="grid lg:grid-cols-2 gap-4"><div className="ent-panel rounded-2xl p-5"><Title icon={<Dices size={14}/>} title="Pick for me" sub="Mood-filtered or completely random"/><div className="flex gap-2"><select value={mood} onChange={e=>setMood(e.target.value)} className="flex-1 rounded-xl border bg-transparent px-3 py-2 text-xs" style={{borderColor:"var(--line)"}}>{moods.map(m=><option key={m}>{m}</option>)}</select><button onClick={()=>setPick(moodPick(items,mood))} className="px-3 rounded-xl bg-fuchsia-500 text-white text-xs">MOOD</button><button onClick={()=>setPick(surprisePick(items))} className="px-3 rounded-xl border text-xs" style={{borderColor:"var(--line)"}}>SURPRISE</button></div>{pick&&<button onClick={()=>onOpen(pick.id)} className="w-full rounded-xl bg-white/5 p-4 mt-3 text-left"><div className="text-[9px] text-cyan-300">TONIGHT'S PICK</div><div className="font-black">{pick.title}</div><div className="text-[10px] mt-1" style={{color:"var(--muted)"}}>{pick.type} · {pick.status} · {pick.tags.join(" · ")}</div></button>}</div>
 <div className="ent-panel rounded-2xl p-5"><Title icon={<Target size={14}/>} title="Blind spots" sub="Areas represented once or not yet completed"/><div className="space-y-3 text-xs"><ChipRow label="Genres" values={blind.genres}/><ChipRow label="Decades" values={blind.decades.map(x=>`${x}s`)}/><ChipRow label="Countries" values={blind.countries}/>{!blind.genres.length&&!blind.decades.length&&!blind.countries.length&&<p style={{color:"var(--muted)"}}>Add release years, genres and countries to reveal blind spots.</p>}</div></div></div>
 <div className="grid lg:grid-cols-2 gap-4"><div className="ent-panel rounded-2xl p-5"><Title icon={<GitBranch size={14}/>} title="Franchise gaps" sub="Missing sequence numbers between tracked entries"/>{gaps.map(g=><div key={g.franchise} className="rounded-xl border p-3 mt-2" style={{borderColor:"var(--line)"}}><div className="font-bold text-sm">{g.franchise}</div><div className="text-[10px] text-amber-300 mt-1">Missing: {g.missing.join(", ")} · {g.owned} tracked</div></div>)}{!gaps.length&&<p className="text-xs" style={{color:"var(--muted)"}}>Add Franchise and Franchise Order in title details to detect skipped entries.</p>}</div>
 <div className="ent-panel rounded-2xl p-5"><Title icon={<Users size={14}/>} title="Creator marathon" sub="See everything tracked by one creator"/><select value={marathon?.name??""} onChange={e=>setCreator(e.target.value)} className="w-full rounded-xl border bg-transparent px-3 py-2 text-xs" style={{borderColor:"var(--line)"}}>{marathons.map(m=><option key={m.name}>{m.name}</option>)}</select>{marathon&&<div className="mt-3"><div className="text-[10px] text-cyan-300">{marathon.completed}/{marathon.items.length} completed · {marathon.avgRating?marathon.avgRating.toFixed(1):"—"} avg</div><div className="space-y-1 mt-2">{marathon.items.map(i=><button key={i.id} onClick={()=>onOpen(i.id)} className="flex w-full text-left text-xs rounded-lg p-2 hover:bg-white/5"><span className={i.status==="completed"?"text-emerald-300":""}>{i.status==="completed"?"✓":"○"}</span><span className="ml-2 truncate">{i.title}</span><span className="ml-auto" style={{color:"var(--muted)"}}>{i.rating??"—"}</span></button>)}</div></div>}</div></div>
 </section>
}
function Title({icon,title,sub}:{icon:React.ReactNode;title:string;sub:string}){return <div className="mb-3"><div className="flex items-center gap-2 font-black text-sm">{icon}{title}</div><p className="text-[10px] mt-1" style={{color:"var(--muted)"}}>{sub}</p></div>}
function ChipRow({label,values}:{label:string;values:(string|number)[]}){return <div><span className="text-[9px] uppercase" style={{color:"var(--muted)"}}>{label}</span><div className="flex flex-wrap gap-1 mt-1">{values.map(v=><span key={String(v)} className="rounded-full bg-white/5 px-2 py-1 text-[9px]">{v}</span>)}</div></div>}
function Empty({text}:{text:string}){return <div className="ent-panel rounded-2xl p-6 text-xs col-span-full" style={{color:"var(--muted)"}}>{text}</div>}
