#!/usr/bin/env node
/** Executes a privacy-safe smoke of the assembled Windows package without external network access. */
import assert from "node:assert/strict";
import fs from "node:fs";
import net from "node:net";
import path from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
const scriptDirectory=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(scriptDirectory,"..",".."),managed=[];
function start(name,args,cwd,env){const child=spawn(process.execPath,args,{cwd,env:{...process.env,...env},stdio:["ignore","pipe","pipe"],windowsHide:true});let log="";const collect=(chunk)=>{log=(log+chunk.toString()).slice(-20000)};child.stdout.on("data",collect);child.stderr.on("data",collect);managed.push({name,child,log:()=>log.replace(/one-time pairing code: \S+/g,"one-time pairing code: [REDACTED]")});return{getLog:()=>log}}
async function waitFor(url,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){try{const response=await fetch(url,{signal:AbortSignal.timeout(1500)});if(response.ok)return}catch{}await new Promise(r=>setTimeout(r,250))}throw new Error(`Timed out waiting for ${url}`)}
async function stopAll(){for(const item of [...managed].reverse())try{item.child.kill()}catch{}await new Promise(r=>setTimeout(r,750));for(const item of managed)if(item.child.exitCode===null)try{item.child.kill("SIGKILL")}catch{}}
async function json(url,options={}){const response=await fetch(url,options);let body={};try{body=await response.json()}catch{}return{response,body}}
function localDate(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function portReleased(port){return new Promise(resolve=>{const socket=net.connect({host:"127.0.0.1",port});socket.once("connect",()=>{socket.destroy();resolve(false)});socket.once("error",()=>resolve(true));setTimeout(()=>{socket.destroy();resolve(false)},1000).unref()})}
const routes=["/","/career","/career/certs","/career/command","/career/daily","/career/jobs","/career/network","/career/portfolio","/career/projects","/career/roadmaps","/career/skills","/entertainment","/health","/health/hydration","/health/mind","/health/nutrition","/health/physique","/health/reports","/health/sleep","/health/supplements","/health/sync","/health/vitals","/projects","/projects/p/package-smoke","/projects/quarry","/projects/smelter","/projects/vault","/workout","/workout/calisthenics","/workout/cardio","/workout/charts","/workout/gym","/workout/kanban","/workout/library","/workout/overview","/workout/prs","/workout/schedule","/workout/skills","/workout/tools"];
const report={classification:"PUBLIC-SANITIZED-AGGREGATE",contract:"kaizen.windows-package-verification",version:"1.0",generatedAt:new Date().toISOString(),packageVersion:fs.readFileSync(path.join(root,"VERSION"),"utf8").trim(),checks:{},passed:false};
try{
  for(const required of ["frontend/server.js","intelligence/dist/src/server.js","runtime/node/node.exe","start-kaizen.cmd","stop-kaizen.cmd"])assert.ok(fs.existsSync(path.join(root,required)),`missing ${required}`);report.checks.layout=true;
  assert.ok(!fs.existsSync(path.join(root,"backend")));report.checks.referenceApiExcluded=true;
  const common={KAIZEN_AI_GATEWAY_URL:"http://127.0.0.1:4317",KAIZEN_AI_PROXY_ORIGIN:"http://127.0.0.1:3000",KAIZEN_AI_ORIGINS:"http://127.0.0.1:3000"};
  const engine=start("Intelligence Engine",[path.join(root,"intelligence/dist/src/server.js")],path.join(root,"intelligence"),{...common,KAIZEN_AI_HOST:"127.0.0.1",KAIZEN_AI_PORT:"4317",KAIZEN_AI_PROVIDER:"mock"});await waitFor("http://127.0.0.1:4317/health");
  const deadline=Date.now()+10000;let pairingCode;while(Date.now()<deadline&&!pairingCode){pairingCode=engine.getLog().match(/one-time pairing code: (\S+)/)?.[1];if(!pairingCode)await new Promise(r=>setTimeout(r,50))}assert.ok(pairingCode,"engine did not emit pairing code");
  start("Frontend",[path.join(root,"frontend/server.js")],path.join(root,"frontend"),{...common,NODE_ENV:"production",HOSTNAME:"127.0.0.1",PORT:"3000",KAIZEN_LOCAL_PACKAGE:"1"});await waitFor("http://127.0.0.1:3000/");
  for(const route of routes){const response=await fetch(`http://127.0.0.1:3000${route}`,{redirect:"follow"});assert.ok(response.status<400,`${route} returned ${response.status}`);await response.arrayBuffer()}report.checks.routes=`${routes.length}/${routes.length}`;
  const home=await fetch("http://127.0.0.1:3000/");const csp=home.headers.get("content-security-policy")||"";assert.ok(csp&&!csp.includes("'unsafe-eval'")&&!csp.includes("upgrade-insecure-requests"));report.checks.localProductionCsp=true;
  const base="http://127.0.0.1:3000/api/ai",cross=await fetch(`${base}/v1/pair`,{method:"POST",headers:{origin:"https://evil.example","x-kaizen-pairing-code":pairingCode}});assert.equal(cross.status,403);
  const paired=await json(`${base}/v1/pair`,{method:"POST",headers:{"x-kaizen-pairing-code":pairingCode}});assert.equal(paired.response.status,200);const auth={authorization:`Bearer ${paired.body.sessionToken}`};
  const status=await json(`${base}/v1/status`,{headers:auth});assert.equal(status.body.model.providerId,"kaizen-mock");assert.equal(status.body.capabilities.nativeToolCalling,false);
  const created=await json(`${base}/v1/requests`,{method:"POST",headers:{...auth,"content-type":"application/json"},body:JSON.stringify({intent:"focus-today",localDate:localDate()})});assert.equal(created.response.status,202);const requestId=created.body.requestId;
  const stream=await fetch(`${base}/v1/requests/${requestId}/events`,{headers:auth}),reader=stream.body.getReader(),decoder=new TextDecoder();let buffer="",eventName="",completed;
  for(;;){const{value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const raw of lines){const line=raw.trim();if(line.startsWith("event:"))eventName=line.slice(6).trim();else if(line.startsWith("data:")){const event=JSON.parse(line.slice(5).trim());if(eventName==="tool.requested"){const request=event.request;assert.deepEqual(request.arguments,{localDate:localDate(),includeCompleted:false,maximumItems:100});const snapshot={contract:"core.today",contractVersion:"1.0",domain:"core",snapshotId:"package:core.1",revision:{installationEpoch:"package",domains:{core:1}},capturedAt:new Date().toISOString(),timezone:"UTC",sensitivity:"personal",trust:"kaizen-derived",data:{localDate:localDate(),tasks:[{id:"package-task",title:"Verify packaged integration",space:"core",priority:"high",completed:false}],scheduled:[],attention:[],deterministicNextAction:{sourceId:"package-task",title:"Verify packaged integration",reason:"Packaged fixed-route evidence",algorithmVersion:"package-1"}},analytics:[],redactions:[{field:"health",reason:"consent"}]};const submitted=await fetch(`${base}/v1/requests/${requestId}/tool-results`,{method:"POST",headers:{...auth,"content-type":"application/json"},body:JSON.stringify({requestId,callId:request.callId,status:"ok",snapshot})});assert.equal(submitted.status,204)}else if(eventName==="response.completed")completed=event.response;else if(eventName==="request.failed")throw new Error(`request failed: ${event.code}`)}}if(completed||done)break}
  assert.equal(completed.title,"Verify packaged integration");assert.equal(completed.model.providerId,"kaizen-mock");await fetch(`${base}/v1/session`,{method:"DELETE",headers:auth});report.checks.coreToday=true;report.checks.crossSiteDenied=true;report.passed=true;
} catch(error){report.errorCode="PACKAGE_VERIFICATION_FAILED";for(const item of managed)console.error(`\n--- ${item.name} log ---\n${item.log()}`);throw error}
finally{await stopAll();await new Promise(r=>setTimeout(r,500));report.checks.portsReleased=await portReleased(3000)&&await portReleased(4317);if(!report.checks.portsReleased)report.passed=false;const reportArg=process.argv.indexOf("--report"),target=reportArg>=0&&process.argv[reportArg+1]?path.resolve(process.argv[reportArg+1]):path.join(root,"package-verification.json");fs.writeFileSync(target,JSON.stringify(report,null,2)+"\n");console.log(report.passed?"Windows package verification: PASS":"Windows package verification: FAIL")}
