"use client";
/** Read-only Core Today Intelligence client with strict tool, source, and freshness verification. */
import type { TodaySnapshot } from "./domainBridge";

export type AiEngineState="offline"|"pairing"|"ready"|"busy"|"failed";
export interface AiResponse{responseId:string;type:"recommendation";title:string;summary:string;rationale:Array<{claim:string;sourceIds:string[];kind:string}>;confidence:number;uncertainty:string[];assumptions:string[];sources:Array<{sourceId:string;domain:string;entityType:string;entityId:string;label:string;snapshotId:string}>;freshness:{generatedAt:string;snapshots:Array<{domain:string;snapshotId:string;capturedAt:string}>;staleDomains:string[];unavailableDomains:string[]};model:{providerId:string;modelId:string}}
export interface FocusCallbacks{onState?:(state:AiEngineState)=>void;onDelta?:(text:string)=>void;signal?:AbortSignal}

const TOKEN_KEY="kaizen.ai.session";
function sourceIds(snapshot:TodaySnapshot):Set<string>{const ids=new Set<string>();snapshot.data.tasks.forEach(x=>ids.add(x.id));snapshot.data.scheduled.forEach(x=>ids.add(x.id));snapshot.data.attention.forEach(x=>ids.add(x.notificationId));if(snapshot.data.deterministicNextAction)ids.add(snapshot.data.deterministicNextAction.sourceId);return ids}
function verifiedResponse(value:AiResponse,snapshot:TodaySnapshot):AiResponse{const available=sourceIds(snapshot),fresh=value.freshness?.snapshots?.length===1&&value.freshness.snapshots[0]?.domain==="core"&&value.freshness.snapshots[0]?.snapshotId===snapshot.snapshotId;const sources=value.sources.every(x=>available.has(x.sourceId)&&x.snapshotId===snapshot.snapshotId);const rationale=value.rationale.every(x=>x.sourceIds.every(id=>available.has(id)&&value.sources.some(source=>source.sourceId===id)));if(value.type!=="recommendation"||!fresh||!sources||!rationale)throw new Error("The Intelligence response failed browser source verification");return value}

export class KaizenAiClient{
  private token:string|null=null;
  constructor(readonly baseUrl=(process.env.NEXT_PUBLIC_KAIZEN_AI_URL||"/api/ai").replace(/\/$/,"")){if(typeof sessionStorage!=="undefined")this.token=sessionStorage.getItem(TOKEN_KEY)}
  get paired(){return!!this.token}
  async pair(code:string):Promise<void>{const response=await fetch(`${this.baseUrl}/v1/pair`,{method:"POST",headers:{"x-kaizen-pairing-code":code}});if(!response.ok)throw new Error((await response.json()).error?.message||"Pairing failed");const data=await response.json();this.token=data.sessionToken;sessionStorage.setItem(TOKEN_KEY,this.token!)}
  clear():void{this.token=null;if(typeof sessionStorage!=="undefined")sessionStorage.removeItem(TOKEN_KEY)}
  private headers(json=false):HeadersInit{if(!this.token)throw new Error("Kaizen Intelligence is not paired");return{authorization:`Bearer ${this.token}`,...(json?{"content-type":"application/json"}:{})}}
  async status():Promise<any>{const response=await fetch(`${this.baseUrl}/v1/status`,{headers:this.headers()});if(response.status===401)this.clear();if(!response.ok)throw new Error("Kaizen Intelligence is unavailable");return response.json()}
  async focusToday(buildSnapshot:()=>TodaySnapshot,callbacks:FocusCallbacks={}):Promise<AiResponse>{callbacks.onState?.("busy");const snapshot=buildSnapshot();const created=await fetch(`${this.baseUrl}/v1/requests`,{method:"POST",headers:this.headers(true),body:JSON.stringify({intent:"focus-today",localDate:snapshot.data.localDate}),signal:callbacks.signal});if(!created.ok)throw new Error((await created.json()).error?.message||"Request could not start");const{requestId}=await created.json();let toolHandled=false;const stream=await fetch(`${this.baseUrl}/v1/requests/${requestId}/events`,{headers:this.headers(),signal:callbacks.signal});if(!stream.ok||!stream.body)throw new Error("Intelligence stream is unavailable");const reader=stream.body.getReader(),decoder=new TextDecoder();let buffer="";
    try{for(;;){const{value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});const blocks=buffer.split("\n\n");buffer=blocks.pop()??"";for(const block of blocks){const event=block.split("\n").find(x=>x.startsWith("event:"))?.slice(6).trim(),raw=block.split("\n").find(x=>x.startsWith("data:"))?.slice(5).trim();if(!event||!raw)continue;const data=JSON.parse(raw);if(event==="tool.requested"){const request=data.request,args=request?.arguments??{},keys=Object.keys(args).sort().join(",");if(toolHandled||request.tool!=="get_today"||request.toolVersion!=="1.0"||request.expectedContract!=="core.today"||request.expectedContractVersion!=="1.0"||keys!=="includeCompleted,localDate,maximumItems"||args.localDate!==snapshot.data.localDate||args.includeCompleted!==false||args.maximumItems!==100)throw new Error("Engine requested an unsupported Core Today route");toolHandled=true;const submitted=await fetch(`${this.baseUrl}/v1/requests/${requestId}/tool-results`,{method:"POST",headers:this.headers(true),body:JSON.stringify({requestId,callId:request.callId,status:"ok",snapshot}),signal:callbacks.signal});if(!submitted.ok)throw new Error("Current Kaizen data was rejected")}else if(event==="generation.delta")callbacks.onDelta?.(data.text);else if(event==="response.completed"){if(!toolHandled)throw new Error("Intelligence completed without validated Core Today evidence");const current=buildSnapshot();if(current.snapshotId!==snapshot.snapshotId||current.data.localDate!==snapshot.data.localDate)throw new Error("Kaizen data changed during interpretation; refresh and try again");const response=verifiedResponse(data.response,snapshot);callbacks.onState?.("ready");return response}else if(event==="request.failed")throw new Error(data.message||"Intelligence request failed");else if(event==="request.cancelled")throw new Error("Intelligence request cancelled")}
      if(done)break}throw new Error("Intelligence stream ended without a response")}catch(error){if(callbacks.signal?.aborted){void fetch(`${this.baseUrl}/v1/requests/${requestId}`,{method:"DELETE",headers:this.headers()}).catch(()=>{});callbacks.onState?.("ready")}else callbacks.onState?.("failed");throw error}finally{reader.releaseLock()}}
}
