/** Browser-side Intelligence foundation for client. */
import type { TodaySnapshot } from "./domainBridge";

export type AiEngineState="offline"|"pairing"|"ready"|"busy"|"failed";
export interface AiResponse{responseId:string;type:string;title:string;summary:string;rationale:Array<{claim:string;sourceIds:string[];kind:string}>;confidence:number;uncertainty:string[];assumptions:string[];sources:Array<{sourceId:string;domain:string;entityType:string;entityId:string;label:string}>;freshness:{generatedAt:string;staleDomains:string[];unavailableDomains:string[]};model:{providerId:string;modelId:string}}
export interface AskCallbacks{onState?:(state:AiEngineState)=>void;onDelta?:(text:string)=>void;signal?:AbortSignal}

const TOKEN_KEY="kaizen.ai.session";
export class KaizenAiClient{
  private token:string|null=null;
  constructor(readonly baseUrl=(process.env.NEXT_PUBLIC_KAIZEN_AI_URL||"/api/ai").replace(/\/$/,"")){if(typeof sessionStorage!=="undefined")this.token=sessionStorage.getItem(TOKEN_KEY)}
  get paired(){return!!this.token}
  async pair(code:string):Promise<void>{const response=await fetch(`${this.baseUrl}/v1/pair`,{method:"POST",headers:{"x-kaizen-pairing-code":code}});if(!response.ok)throw new Error((await response.json()).error?.message||"Pairing failed");const data=await response.json();this.token=data.sessionToken;sessionStorage.setItem(TOKEN_KEY,this.token!)}
  clear():void{this.token=null;if(typeof sessionStorage!=="undefined")sessionStorage.removeItem(TOKEN_KEY)}
  private headers(json=false):HeadersInit{if(!this.token)throw new Error("Kaizen Intelligence is not paired");return{authorization:`Bearer ${this.token}`,...(json?{"content-type":"application/json"}:{})}}
  async status():Promise<any>{const response=await fetch(`${this.baseUrl}/v1/status`,{headers:this.headers()});if(response.status===401)this.clear();if(!response.ok)throw new Error("Kaizen Intelligence is unavailable");return response.json()}
  async ask(prompt:string,buildSnapshot:()=>TodaySnapshot,callbacks:AskCallbacks={}):Promise<AiResponse>{callbacks.onState?.("busy");const created=await fetch(`${this.baseUrl}/v1/requests`,{method:"POST",headers:this.headers(true),body:JSON.stringify({prompt,intent:"focus-today"}),signal:callbacks.signal});if(!created.ok)throw new Error((await created.json()).error?.message||"Request could not start");const{requestId}=await created.json();const stream=await fetch(`${this.baseUrl}/v1/requests/${requestId}/events`,{headers:this.headers(),signal:callbacks.signal});if(!stream.ok||!stream.body)throw new Error("Intelligence stream is unavailable");const reader=stream.body.getReader(),decoder=new TextDecoder();let buffer="";
    try{for(;;){const{value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});const blocks=buffer.split("\n\n");buffer=blocks.pop()??"";for(const block of blocks){const event=block.split("\n").find(x=>x.startsWith("event:"))?.slice(6).trim(),raw=block.split("\n").find(x=>x.startsWith("data:"))?.slice(5).trim();if(!event||!raw)continue;const data=JSON.parse(raw);if(event==="tool.requested"){if(data.request.tool!=="get_today")throw new Error("Engine requested an unsupported tool");const snapshot=buildSnapshot();const submitted=await fetch(`${this.baseUrl}/v1/requests/${requestId}/tool-results`,{method:"POST",headers:this.headers(true),body:JSON.stringify({requestId,callId:data.request.callId,status:"ok",snapshot}),signal:callbacks.signal});if(!submitted.ok)throw new Error("Current Kaizen data was rejected")}else if(event==="generation.delta")callbacks.onDelta?.(data.text);else if(event==="response.completed"){callbacks.onState?.("ready");return data.response}else if(event==="request.failed")throw new Error(data.message||"Intelligence request failed");else if(event==="request.cancelled")throw new Error("Intelligence request cancelled")}
      if(done)break}throw new Error("Intelligence stream ended without a response")}catch(error){callbacks.onState?.("failed");throw error}finally{reader.releaseLock()}}
}
