/** Versioned whole-product browser backup with strict validation and rollback restore. */
export const AUTHORITATIVE_KEYS=["kaizen.tasks","kaizen.notes","kaizen.career","kaizen.workout","kaizen.forge","kaizen.health","kaizen.entertainment","kaizen.notifications","kaizen.habits","kaizen.focus","kaizen.theme","kaizen.profile"] as const;
export type AuthoritativeKey=typeof AUTHORITATIVE_KEYS[number];
export interface StorageLike{getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void}
export interface KaizenBackup{classification:"KAIZEN-LOCAL-BACKUP";schemaVersion:1|2;exportedAt:string;data:Partial<Record<AuthoritativeKey,string|null>>}
const BLOCKED=new Set(["__proto__","prototype","constructor"]),MAX_BACKUP_CHARS=25_000_000,MAX_VALUE_CHARS=8_000_000;
const LEGACY_KEYS=["kaizen.tasks","kaizen.notes","kaizen.career","kaizen.workout","kaizen.forge","kaizen.health","kaizen.entertainment","kaizen.notifications","kaizen.habits","kaizen.focus","kaizen.theme"] as const;
function safe(value:unknown,depth=0,budget={nodes:0}):void{if(++budget.nodes>200_000||depth>40)throw new Error("Backup data is too complex");if(Array.isArray(value)){if(value.length>30_000)throw new Error("Backup array is too large");value.forEach(item=>safe(item,depth+1,budget))}else if(value&&typeof value==="object"){for(const[key,item]of Object.entries(value as Record<string,unknown>)){if(BLOCKED.has(key))throw new Error("Backup contains an unsafe object key");safe(item,depth+1,budget)}}}
function validateRaw(key:AuthoritativeKey,raw:string|null):void{if(raw===null||raw===undefined)return;if(raw.length>MAX_VALUE_CHARS)throw new Error(`${key} exceeds the backup value limit`);if(key==="kaizen.theme"){if(raw!=="dark"&&raw!=="light")throw new Error("Backup theme is invalid");return}let parsed:unknown;try{parsed=JSON.parse(raw)}catch{throw new Error(`${key} is not valid JSON`)}safe(parsed)}
export function createBackup(storage:StorageLike,now=new Date()):KaizenBackup{const data={} as Record<AuthoritativeKey,string|null>;for(const key of AUTHORITATIVE_KEYS)data[key]=storage.getItem(key);return{classification:"KAIZEN-LOCAL-BACKUP",schemaVersion:2,exportedAt:now.toISOString(),data}}
export function parseBackup(text:string):KaizenBackup{if(text.length>MAX_BACKUP_CHARS)throw new Error("Backup file is too large");let value:unknown;try{value=JSON.parse(text)}catch{throw new Error("Backup file is not valid JSON")}safe(value);const backup=value as Partial<KaizenBackup>;if(backup.classification!=="KAIZEN-LOCAL-BACKUP"||(backup.schemaVersion!==1&&backup.schemaVersion!==2)||!backup.data||typeof backup.data!=="object"||Array.isArray(backup.data))throw new Error("Backup envelope is invalid");const keys=Object.keys(backup.data);if(keys.some(key=>!AUTHORITATIVE_KEYS.includes(key as AuthoritativeKey)))throw new Error("Backup keys do not match the authoritative product state");const required=backup.schemaVersion===1?LEGACY_KEYS:AUTHORITATIVE_KEYS;if(required.some(key=>!(key in backup.data!)))throw new Error("Backup keys do not match the authoritative product state");for(const key of AUTHORITATIVE_KEYS)validateRaw(key,(backup.data as Record<string,unknown>)[key] as string|null|undefined ?? null);if(!Number.isFinite(Date.parse(String(backup.exportedAt))))throw new Error("Backup timestamp is invalid");return backup as KaizenBackup}
export function restoreBackup(storage:StorageLike,backup:KaizenBackup):void{const originals=new Map(AUTHORITATIVE_KEYS.map(key=>[key,storage.getItem(key)]));try{for(const key of AUTHORITATIVE_KEYS){const value=backup.data[key]??null;if(value===null)storage.removeItem(key);else storage.setItem(key,value)}}catch(error){originals.forEach((value,key)=>{try{if(value===null)storage.removeItem(key);else storage.setItem(key,value)}catch{}});throw error}}
