"use client";
import type { EntertainmentItem, MediaStatus, MediaType } from "./entertainmentTypes";
import { assertImportFileSize } from "./security";

export type ImportSource="auto"|"mal"|"anilist"|"trakt"|"simkl"|"kitsu";
const uid=()=>Math.random().toString(36).slice(2,10)+Date.now().toString(36);
const clean=(v:unknown,max=5000)=>String(v??"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim().slice(0,max);
const date=(v:unknown)=>{const s=clean(v,20);return /^\d{4}-\d{2}-\d{2}/.test(s)&&!s.startsWith("0000-")?s.slice(0,10):undefined};
function status(v:unknown):MediaStatus{const s=clean(v,50).toLowerCase().replace(/[ _-]/g,"");if(["completed","complete"].includes(s))return"completed";if(["watching","reading","current","inprogress"].includes(s))return"in-progress";if(["onhold","paused"].includes(s))return"paused";if(["dropped","dnf"].includes(s))return"dropped";return"planned"}
function mediaType(v:unknown,fallback:MediaType="movie"):MediaType{const s=clean(v,50).toLowerCase();if(s.includes("anime"))return"anime";if(s.includes("manga"))return"manga";if(s.includes("comic"))return"comic";if(s.includes("book")||s.includes("novel"))return"book";if(s.includes("show")||s.includes("series")||s==="tv")return"series";if(s.includes("movie")||s.includes("film"))return"movie";return fallback}
function base(input:Partial<EntertainmentItem>&Pick<EntertainmentItem,"title"|"type">):EntertainmentItem{const now=Date.now();return{id:uid(),provider:"manual",genres:[],creators:[],cast:[],studios:[],status:"planned",progress:{},repeats:0,priority:"medium",queueOrder:now,tags:["imported"],favorite:false,archived:false,createdAt:now,updatedAt:now,...input}}

function parseMalXml(text:string):EntertainmentItem[]{
 if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error("MAL XML document types and entities are not allowed.");
 const doc=new DOMParser().parseFromString(text,"application/xml");if(doc.querySelector("parsererror"))throw new Error("Invalid MAL XML export.");const out:EntertainmentItem[]=[];
 doc.querySelectorAll("anime").forEach(n=>{const get=(x:string)=>n.querySelector(x)?.textContent??"",title=clean(get("series_title"),300);if(!title)return;const total=Number(get("series_episodes"))||undefined,current=Number(get("my_watched_episodes"))||0;out.push(base({provider:"mal",providerId:clean(get("series_animedb_id"),128)||undefined,type:"anime",title,status:status(get("my_status")),rating:Number(get("my_score"))||undefined,startedAt:date(get("my_start_date")),completedAt:date(get("my_finish_date")),repeats:Number(get("my_times_watched"))||0,progress:{currentEpisode:current,totalEpisodes:total},tags:["imported","mal"]}))});
 doc.querySelectorAll("manga").forEach(n=>{const get=(x:string)=>n.querySelector(x)?.textContent??"",title=clean(get("manga_title")||get("series_title"),300);if(!title)return;out.push(base({provider:"mal",providerId:clean(get("manga_mangadb_id")||get("series_mangadb_id"),128)||undefined,type:"manga",title,status:status(get("my_status")),rating:Number(get("my_score"))||undefined,startedAt:date(get("my_start_date")),completedAt:date(get("my_finish_date")),repeats:Number(get("my_times_read")||get("my_rereadingg"))||0,progress:{currentChapter:Number(get("my_read_chapters"))||0,totalChapters:Number(get("manga_chapters"))||undefined,currentVolume:Number(get("my_read_volumes"))||0,totalVolumes:Number(get("manga_volumes"))||undefined},tags:["imported","mal"]}))});
 return out;
}
function parseAniListJson(data:any):EntertainmentItem[]{
 const lists=data?.MediaListCollection?.lists??data?.data?.MediaListCollection?.lists??data?.lists??[];const entries=Array.isArray(data)?data:lists.flatMap((l:any)=>l.entries??[]);
 return entries.map((e:any)=>{const m=e.media??e.Media??{},type=mediaType(m.type??e.type,"anime"),title=clean(m.title?.english??m.title?.romaji??m.title??e.title,300);if(!title)return null;return base({provider:"anilist",providerId:clean(m.id??e.mediaId,128)||undefined,type,title,status:status(e.status),rating:Number(e.score)||undefined,startedAt:fuzzyDate(e.startedAt),completedAt:fuzzyDate(e.completedAt),repeats:Number(e.repeat)||0,notes:clean(e.notes)||undefined,releaseYear:Number(m.startDate?.year)||undefined,genres:Array.isArray(m.genres)?m.genres.map((x:any)=>clean(x,80)).filter(Boolean):[],progress:type==="manga"?{currentChapter:Number(e.progress)||0,totalChapters:Number(m.chapters)||undefined,currentVolume:Number(e.progressVolumes)||0,totalVolumes:Number(m.volumes)||undefined}:{currentEpisode:Number(e.progress)||0,totalEpisodes:Number(m.episodes)||undefined},tags:["imported","anilist"]})}).filter((x:any):x is EntertainmentItem=>!!x)
}
function fuzzyDate(v:any){if(!v)return undefined;if(typeof v==="string")return date(v);if(v.year)return `${v.year}-${String(v.month||1).padStart(2,"0")}-${String(v.day||1).padStart(2,"0")}`;return undefined}
function parseCsv(text:string,source:Exclude<ImportSource,"auto"|"mal"|"anilist"|"kitsu">):EntertainmentItem[]{
 const rows=csvRows(text);if(rows.length<2)return[];const h=rows[0].map(x=>x.trim().toLowerCase().replace(/[ _-]/g,"")),idx=(...names:string[])=>names.map(n=>h.indexOf(n)).find(i=>i>=0)??-1,get=(r:string[],...names:string[])=>{const i=idx(...names);return i>=0?r[i]??"":""};
 return rows.slice(1).map(r=>{const title=clean(get(r,"title","name"),300);if(!title)return null;const type=mediaType(get(r,"type","mediatype"),"movie"),providerId=clean(get(r,source+"id","traktid","simklid","tmdbid","id"),128)||undefined,progress=Number(get(r,"progress","watchedepisodes","readchapters"))||0,total=Number(get(r,"total","episodes","chapters","pages"))||undefined;return base({provider:source,providerId,type,title,releaseYear:Number(get(r,"year","releaseyear"))||undefined,status:status(get(r,"status","watchstatus")),rating:Number(get(r,"rating","score"))||undefined,startedAt:date(get(r,"startedat","startdate")),completedAt:date(get(r,"completedat","watchedat","finishdate")),repeats:Number(get(r,"repeats","rewatches"))||0,progress:type==="book"?{currentPage:progress,totalPages:total}:type==="manga"||type==="comic"?{currentChapter:progress,totalChapters:total}:type==="movie"?{watched:status(get(r,"status","watchstatus"))==="completed"}:{currentEpisode:progress,totalEpisodes:total},tags:["imported",source]})}).filter((x:any):x is EntertainmentItem=>!!x)
}
function parseKitsuJson(data:any):EntertainmentItem[]{
 const included=new Map((data.included??[]).map((x:any)=>[`${x.type}:${x.id}`,x]));return (data.data??data??[]).map((e:any)=>{const a=e.attributes??e,rel=e.relationships?.media?.data,media=rel?included.get(`${rel.type}:${rel.id}`) as any:undefined,m=media?.attributes??{},title=clean(m.canonicalTitle??m.titles?.en??a.title,300);if(!title)return null;const type=mediaType(rel?.type??m.subtype??a.type,"anime"),total=Number(m.episodeCount??m.chapterCount)||undefined;return base({provider:"kitsu",providerId:clean(rel?.id??e.id,128)||undefined,type,title,status:status(a.status),rating:a.ratingTwenty?Number(a.ratingTwenty)/2:undefined,startedAt:date(a.startedAt),completedAt:date(a.finishedAt),repeats:Number(a.reconsumingCount)||0,description:clean(m.synopsis)||undefined,releaseYear:Number(String(m.startDate??"").slice(0,4))||undefined,progress:type==="manga"?{currentChapter:Number(a.progress)||0,totalChapters:total}:{currentEpisode:Number(a.progress)||0,totalEpisodes:total},tags:["imported","kitsu"]})}).filter((x:any):x is EntertainmentItem=>!!x)
}
function csvRows(text:string){const rows:string[][]=[];let row:string[]=[],field="",quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(quote){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quote=false;else field+=c}else if(c==='"')quote=true;else if(c===','){row.push(field);field=""}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=""}else if(c!=="\r")field+=c}if(field||row.length){row.push(field);rows.push(row)}return rows.filter(r=>r.some(Boolean))}

async function importText(file:File){
 const bytes=new Uint8Array(await file.slice(0,2).arrayBuffer()),gzip=file.name.toLowerCase().endsWith(".gz")||(bytes[0]===0x1f&&bytes[1]===0x8b);if(!gzip)return file.text();if(typeof DecompressionStream==="undefined")throw new Error("This browser cannot decompress MAL .gz exports. Extract the XML first.");
 const reader=file.stream().pipeThrough(new DecompressionStream("gzip")).getReader(),decoder=new TextDecoder(),parts:string[]=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;if(value){total+=value.byteLength;if(total>20*1024*1024){await reader.cancel();throw new Error("Expanded import exceeds 20 MB.")}parts.push(decoder.decode(value,{stream:true}))}}parts.push(decoder.decode());return parts.join("")
}
export async function parseEntertainmentImport(file:File,source:ImportSource):Promise<EntertainmentItem[]>{
 assertImportFileSize(file);const text=await importText(file),trim=text.trim();if(!trim)throw new Error("Import file is empty.");let detected=source;if(source==="auto"){if(trim.startsWith("<"))detected="mal";else if(file.name.toLowerCase().endsWith(".csv"))detected=/simkl/i.test(file.name)?"simkl":"trakt";else{const data=JSON.parse(trim);if(data?.MediaListCollection||data?.data?.MediaListCollection||data?.lists)detected="anilist";else if(data?.included||data?.data?.[0]?.relationships)detected="kitsu";else if(/simkl/i.test(file.name))detected="simkl";else detected="anilist"}}
 let items:EntertainmentItem[]=[];if(detected==="mal")items=parseMalXml(text);else if(detected==="anilist")items=parseAniListJson(JSON.parse(text));else if(detected==="kitsu")items=parseKitsuJson(JSON.parse(text));else items=parseCsv(text,detected as "trakt"|"simkl");if(items.length>10_000)throw new Error("Import exceeds 10,000 titles.");if(!items.length)throw new Error("No supported media entries found.");return items;
}
