/** Pure domain utilities for entertainment i18n. */
export type EntertainmentLanguage="en"|"ta"|"hi";
export const ENTERTAINMENT_LANGUAGES:{id:EntertainmentLanguage;label:string;providerLocale:string}[]=[{id:"en",label:"English",providerLocale:"en-US"},{id:"ta",label:"தமிழ்",providerLocale:"ta-IN"},{id:"hi",label:"हिन्दी",providerLocale:"hi-IN"}];
const copy={
 en:{now:"Now Playing",library:"Library",collections:"Collections",calendar:"Calendar",history:"History",archive:"Archive",discover:"Discover",stats:"Stats",social:"Social",studio:"Studio",quickAdd:"Quick Add",search:"Search titles, creators, tags, notes…",marquee:"TONIGHT'S MARQUEE",heroA:"Your stories.",heroB:"One living archive.",heroText:"Track every page, episode and frame without turning leisure into homework.",inMotion:"IN MOTION",queued:"QUEUED",finished:"FINISHED",timeInside:"TIME INSIDE",continue:"Continue the story",upNext:"Up next",viewAll:"VIEW ALL",language:"Language"},
 ta:{now:"தற்போது",library:"நூலகம்",collections:"தொகுப்புகள்",calendar:"நாட்காட்டி",history:"வரலாறு",archive:"காப்பகம்",discover:"கண்டறிக",stats:"புள்ளிவிவரம்",social:"சமூகம்",studio:"படைப்பகம்",quickAdd:"விரைவு சேர்ப்பு",search:"தலைப்புகள், படைப்பாளர்கள், குறிச்சொற்கள்…",marquee:"இன்றைய திரை",heroA:"உங்கள் கதைகள்.",heroB:"ஒரே உயிருள்ள காப்பகம்.",heroText:"ஒவ்வொரு பக்கம், அத்தியாயம், காட்சியையும் எளிதாகப் பதிவு செய்யுங்கள்.",inMotion:"தொடர்கிறது",queued:"வரிசையில்",finished:"முடிந்தது",timeInside:"செலவிட்ட நேரம்",continue:"கதையைத் தொடருங்கள்",upNext:"அடுத்து",viewAll:"அனைத்தும்",language:"மொழி"},
 hi:{now:"अभी जारी",library:"लाइब्रेरी",collections:"संग्रह",calendar:"कैलेंडर",history:"इतिहास",archive:"अभिलेख",discover:"खोजें",stats:"आँकड़े",social:"समूह",studio:"रचना",quickAdd:"तुरंत जोड़ें",search:"शीर्षक, निर्माता, टैग और नोट खोजें…",marquee:"आज की प्रस्तुति",heroA:"आपकी कहानियाँ।",heroB:"एक जीवंत अभिलेख।",heroText:"हर पन्ना, एपिसोड और फ़्रेम को सहजता से दर्ज करें।",inMotion:"जारी",queued:"कतार",finished:"पूर्ण",timeInside:"कुल समय",continue:"कहानी जारी रखें",upNext:"अगला",viewAll:"सभी देखें",language:"भाषा"},
} as const;
export type EntertainmentCopyKey=keyof typeof copy.en;
export function entertainmentCopy(language:string,key:EntertainmentCopyKey){const lang=(language in copy?language:"en") as keyof typeof copy;return copy[lang][key]}
export function providerLocale(language:string){return ENTERTAINMENT_LANGUAGES.find(x=>x.id===language)?.providerLocale??"en-US"}
