/** Pure domain utilities for entertainment analytics. */
import type { EntertainmentItem, MediaType } from "./entertainmentTypes";
const norm=(s:string)=>s.trim().toLowerCase();
const overlap=(a:string[],b:string[])=>{const B=new Set(b.map(norm));return a.reduce((n,x)=>n+(B.has(norm(x))?1:0),0)};
export interface Recommendation { item:EntertainmentItem;score:number;reasons:string[];because:string[] }
export function recommendations(items:EntertainmentItem[],limit=8):Recommendation[]{
 const liked=items.filter(i=>i.favorite||(i.rating??0)>=8),planned=items.filter(i=>i.status==="planned"&&!i.archived);
 return planned.map(item=>{let score=0;const reasons=new Set<string>(),because=new Set<string>();for(const source of liked){const g=overlap(item.genres,source.genres),t=overlap(item.tags,source.tags),c=overlap(item.creators,source.creators),s=overlap(item.studios,source.studios);if(g){score+=g*3;reasons.add(`${g} shared genre${g>1?"s":""}`)}if(t){score+=t*2;reasons.add("matching mood/tags")}if(c){score+=c*5;reasons.add("same creator")}if(s){score+=s*4;reasons.add("same studio")}if(item.type===source.type)score+=1;if(g||t||c||s)because.add(source.title)}return{item,score,reasons:Array.from(reasons),because:Array.from(because).slice(0,3)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.item.queueOrder-b.item.queueOrder).slice(0,limit)
}
export function moodOptions(items:EntertainmentItem[]){return Array.from(new Set(items.filter(i=>i.status==="planned").flatMap(i=>i.tags))).sort()}
export function moodPick(items:EntertainmentItem[],mood:string,random=Math.random){const pool=items.filter(i=>i.status==="planned"&&!i.archived&&i.tags.some(t=>norm(t)===norm(mood)));return pool.length?pool[Math.floor(random()*pool.length)]:undefined}
export function surprisePick(items:EntertainmentItem[],random=Math.random){const pool=items.filter(i=>!i.archived);return pool.length?pool[Math.floor(random()*pool.length)]:undefined}
export function explorationScore(items:EntertainmentItem[]){const consumed=items.filter(i=>i.status==="completed"||i.status==="in-progress"),genres=new Set(consumed.flatMap(i=>i.genres.map(norm))),creators=new Set(consumed.flatMap(i=>i.creators.map(norm))),decades=new Set(consumed.map(i=>i.releaseYear?Math.floor(i.releaseYear/10)*10:undefined).filter((x):x is number=>!!x)),countries=new Set(consumed.flatMap(i=>(i.countries??[]).map(norm))),types=new Set(consumed.map(i=>i.type));const score=Math.round(Math.min(30,genres.size/12*30)+Math.min(25,creators.size/10*25)+Math.min(20,decades.size/6*20)+Math.min(15,countries.size/6*15)+Math.min(10,types.size/6*10));return{score,genres:genres.size,creators:creators.size,decades:decades.size,countries:countries.size,types:types.size}}
export function blindSpots(items:EntertainmentItem[]){const consumed=items.filter(i=>i.status==="completed"),genreCounts=new Map<string,number>();for(const i of consumed)for(const g of i.genres)genreCounts.set(g,(genreCounts.get(g)??0)+1);const known=Array.from(new Set(items.flatMap(i=>i.genres))).sort(),genres=known.filter(g=>(genreCounts.get(g)??0)<=1);const years=consumed.map(i=>i.releaseYear).filter((x):x is number=>!!x),decades:number[]=[];if(years.length){const min=Math.max(1950,Math.floor(Math.min(...years)/10)*10),max=Math.floor(new Date().getFullYear()/10)*10;for(let y=min;y<=max;y+=10)if(!years.some(x=>Math.floor(x/10)*10===y))decades.push(y)}const countryCounts=new Map<string,number>();for(const i of consumed)for(const c of i.countries??[])countryCounts.set(c,(countryCounts.get(c)??0)+1);return{genres:genres.slice(0,8),decades:decades.slice(-8),countries:Array.from(new Set(items.flatMap(i=>i.countries??[]))).filter(c=>(countryCounts.get(c)??0)<=1).slice(0,8)}}
export function franchiseGaps(items:EntertainmentItem[]){const groups=new Map<string,EntertainmentItem[]>();for(const i of items)if(i.franchise&&i.franchiseOrder){const key=norm(i.franchise);groups.set(key,[...(groups.get(key)??[]),i])}return Array.from(groups.entries()).flatMap(([key,entries])=>{const orders=entries.map(i=>i.franchiseOrder!).sort((a,b)=>a-b),missing:number[]=[];for(let n=orders[0];n<=orders[orders.length-1];n++)if(!orders.includes(n))missing.push(n);return missing.length?[{franchise:entries[0].franchise!,missing,owned:orders.length,entries:entries.sort((a,b)=>a.franchiseOrder!-b.franchiseOrder!)}]:[]})}
export function creatorMarathons(items:EntertainmentItem[]){const map=new Map<string,{name:string;items:EntertainmentItem[]}>();for(const i of items)for(const c of i.creators){const key=norm(c),v=map.get(key)??{name:c,items:[]};v.items.push(i);map.set(key,v)}return Array.from(map.values()).map(x=>({...x,completed:x.items.filter(i=>i.status==="completed").length,avgRating:avg(x.items.map(i=>i.rating).filter((n):n is number=>!!n))})).sort((a,b)=>b.items.length-a.items.length||b.avgRating-a.avgRating)}
function avg(a:number[]){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
