/** Pure domain utilities for notification types. */
export type NotificationSection="workout"|"career"|"projects"|"health"|"entertainment"|"system";
export type NotificationKind="reminder"|"progress"|"alert"|"celebration"|"digest";
export type NotificationPriority="low"|"normal"|"high"|"critical";
export type NotificationFrequency="realtime"|"daily"|"weekly"|"smart";
export interface KaizenNotification {id:string;sourceKey:string;section:NotificationSection;kind:NotificationKind;priority:NotificationPriority;title:string;body:string;createdAt:number;scheduledFor?:number;actionHref?:string;readAt?:number;dismissedAt?:number;browserDeliveredAt?:number}
export interface SectionNotificationSettings {enabled:boolean;reminder:boolean;progress:boolean;alert:boolean;celebration:boolean}
export interface NotificationSettings {enabled:boolean;frequency:NotificationFrequency;quietStart:number;quietEnd:number;dnd:boolean;snoozedUntil?:number;browser:boolean;sound:boolean;digestTime:string;weeklyDay:number;sections:Record<Exclude<NotificationSection,"system">,SectionNotificationSettings>}
export type SetupSection="workout"|"career"|"projects"|"health"|"entertainment";
export interface NotificationSetupState {confirmed:Record<SetupSection,boolean>;entertainmentManual:boolean;updatedAt?:number}
export interface NotificationState {schemaVersion:2;items:KaizenNotification[];settings:NotificationSettings;setup:NotificationSetupState;lastEvaluatedAt?:number}
const EMPTY_SETUP:NotificationSetupState={confirmed:{workout:false,career:false,projects:false,health:false,entertainment:false},entertainmentManual:false};
const section=():SectionNotificationSettings=>({enabled:true,reminder:true,progress:true,alert:true,celebration:true});
export const DEFAULT_NOTIFICATION_SETTINGS:NotificationSettings={enabled:true,frequency:"smart",quietStart:22,quietEnd:8,dnd:false,browser:false,sound:false,digestTime:"20:00",weeklyDay:0,sections:{workout:section(),career:section(),projects:section(),health:section(),entertainment:section()}};
export const EMPTY_NOTIFICATION_STATE:NotificationState={schemaVersion:2,items:[],settings:DEFAULT_NOTIFICATION_SETTINGS,setup:EMPTY_SETUP};
export function notificationSectionForPath(pathname:string):Exclude<NotificationSection,"system">|null {if(pathname.startsWith("/workout"))return"workout";if(pathname.startsWith("/career"))return"career";if(pathname.startsWith("/projects"))return"projects";if(pathname.startsWith("/health"))return"health";if(pathname.startsWith("/entertainment"))return"entertainment";return null}
export function notificationVisibleInContext(section:NotificationSection,current:Exclude<NotificationSection,"system">|null){return section==="system"||section===current}
export function notificationStillRelevant(item:Pick<KaizenNotification,"sourceKey">,setup:NotificationSetupState){if(!item.sourceKey.startsWith("setup:"))return true;const part=item.sourceKey.split(":")[1] as SetupSection|"global";return part==="global"?Object.values(setup.confirmed).some(v=>!v):!setup.confirmed[part]}
export function migrateNotifications(raw:Partial<NotificationState>|null|undefined):NotificationState{if(!raw||typeof raw!=="object")return EMPTY_NOTIFICATION_STATE;const settings={...DEFAULT_NOTIFICATION_SETTINGS,...(raw.settings??{}),sections:{workout:{...section(),...raw.settings?.sections?.workout},career:{...section(),...raw.settings?.sections?.career},projects:{...section(),...raw.settings?.sections?.projects},health:{...section(),...raw.settings?.sections?.health},entertainment:{...section(),...raw.settings?.sections?.entertainment}}};const setup={...EMPTY_SETUP,...(raw.setup??{}),confirmed:{...EMPTY_SETUP.confirmed,...(raw.setup?.confirmed??{})}};return{schemaVersion:2,items:Array.isArray(raw.items)?raw.items.filter(x=>x&&typeof x.id==="string"&&typeof x.sourceKey==="string").slice(0,2000):[],settings,setup,lastEvaluatedAt:raw.lastEvaluatedAt}}
