import type { NotificationKind,NotificationPriority,NotificationSection } from "./notificationTypes";
export interface NotificationCandidate {sourceKey:string;section:NotificationSection;kind:NotificationKind;priority:NotificationPriority;title:string;body:string;actionHref?:string;scheduledFor?:number}
export interface NotificationSnapshot {workout:any;career:any;forge:any;health:any;entertainment:any;tasks:any[];setup?:any}
const DAY=86_400_000;
const localDate=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`};
const dateAt=(iso:string)=>{const n=new Date(`${iso}T12:00:00`).getTime();return Number.isFinite(n)?n:0};
const daysFrom=(iso:string,now:number)=>Math.floor((now-dateAt(iso))/DAY);
const daysUntil=(iso:string,now:number)=>Math.ceil((dateAt(iso)-now)/DAY);
const C=(sourceKey:string,section:NotificationSection,kind:NotificationKind,priority:NotificationPriority,title:string,body:string,actionHref?:string):NotificationCandidate=>({sourceKey,section,kind,priority,title,body,actionHref});
export function evaluateNotificationRules(s:NotificationSnapshot,nowDate=new Date()):NotificationCandidate[]{const now=nowDate.getTime(),today=localDate(nowDate),hour=nowDate.getHours(),out:NotificationCandidate[]=[],confirmed=s.setup?.confirmed??{};
 // Section setup — explicit confirmation prevents seeded/default values being mistaken for user data.
 if(!confirmed.workout){const missing=[!(s.workout.bodyweight??[]).length&&"bodyweight",!(s.workout.routines??[]).length&&"a routine"].filter(Boolean);out.push(C("setup:workout:v1","workout","alert","high","Workout setup needs your data",`Add ${missing.length?missing.join(" and "):"your training preferences"}, then confirm Workout setup in the notification checklist.`,"/workout/overview"))}
 if(!confirmed.career){const missing=[!(s.career.skills??[]).length&&"skills",!(s.career.goals??[]).length&&"career goals"].filter(Boolean);out.push(C("setup:career:v1","career","alert","high","Career setup is incomplete",`Review your roadmap and add ${missing.length?missing.join(" and "):"your current career targets"}.`,"/career/projects"))}
 if(!confirmed.projects)out.push(C("setup:projects:v1","projects","alert","high","Create your first real project","Demo/empty workspace data is not a personal project. Add or confirm your active Forge workspace.","/projects"));
 if(!confirmed.health)out.push(C("setup:health:v1","health","alert","critical","Confirm your Health profile","Age, height, gender, city, sleep target and goals drive health calculations. Review them before trusting recommendations.","/health/sync"));
 if(!confirmed.entertainment)out.push(C("setup:entertainment:v1","entertainment","alert","normal","Choose Entertainment data sources","Configure MAL/TMDB/Books providers or confirm that you will use manual entries.","/entertainment"));
 const missingSetup=(["workout","career","projects","health","entertainment"] as const).filter(x=>!confirmed[x]);if(missingSetup.length)out.push(C(`setup:global:${missingSetup.join("-")}`,"system","alert","high","Profile setup needs attention",`${missingSetup.length} section${missingSetup.length===1?"":"s"} still need personal data or confirmation. Open Data Setup in notifications.`));
 // Workout — schedule, missed sessions, weigh-in and PRs.
 const todayRoutines=(s.workout.routines??[]).filter((r:any)=>r.dayOfWeek===nowDate.getDay());for(const r of todayRoutines)out.push(C(`workout:schedule:${r.id}:${today}`,"workout","reminder","normal","Workout scheduled",`${r.name} is on today's plan. Warm up and equipment ready?`,"/workout/schedule"));
 const yesterday=new Date(now-DAY),yday=localDate(yesterday),yRoutines=(s.workout.routines??[]).filter((r:any)=>r.dayOfWeek===yesterday.getDay()),trainedYesterday=(s.workout.sessions??[]).some((x:any)=>x.date===yday&&x.endedAt);for(const r of yRoutines)if(!trainedYesterday)out.push(C(`workout:missed:${r.id}:${yday}`,"workout","alert","high","Missed workout",`You missed yesterday's ${r.name}. Reschedule it or adjust the plan.`,"/workout/schedule"));
 if(hour>=7&&!(s.workout.bodyweight??[]).some((x:any)=>x.date===today))out.push(C(`workout:weighin:${today}`,"workout","reminder","low","Morning weigh-in","Log bodyweight before breakfast for a cleaner trend.","/workout/overview"));
 for(const pr of (s.workout.prs??[]).filter((x:any)=>x.date===today)){const ex=(s.workout.exercises??[]).find((e:any)=>e.id===pr.exerciseId);out.push(C(`workout:pr:${pr.id}`,"workout","celebration","normal","New personal record!",`${ex?.name??"Exercise"}: ${pr.value}${ex?.unit==="kg"?" kg":""}${pr.reps?` × ${pr.reps}`:""}.`,"/workout/prs"))}
 // Career — expiry, stale contacts, follow-ups, applications and skill decay.
 for(const course of s.career.courses??[]){if(!course.expiryDate)continue;const d=daysUntil(course.expiryDate,now);if(d<=0)out.push(C(`career:cert-expired:${course.id}:${course.expiryDate}`,"career","alert","high","Certification expired",`${course.name} has expired. Plan renewal.`,"/career/certs"));else if(d<=30)out.push(C(`career:cert-30:${course.id}:${course.expiryDate}`,"career","reminder","high","Certification expires soon",`${course.name} expires in ${d} days.`,"/career/certs"));else if(d<=90)out.push(C(`career:cert-90:${course.id}:${course.expiryDate}`,"career","reminder","normal","Certification renewal window",`${course.name} expires in ${d} days.`,"/career/certs"))}
 for(const contact of s.career.contacts??[]){if(contact.lastContactAt&&now-contact.lastContactAt>=90*DAY)out.push(C(`career:stale-contact:${contact.id}:${Math.floor(now/(30*DAY))}`,"career","reminder","normal","Stale contact",`You haven't spoken to ${contact.name} in ${Math.floor((now-contact.lastContactAt)/DAY)} days.`,"/career/network"));if(contact.nextFollowUpAt&&contact.nextFollowUpAt<=now)out.push(C(`career:followup:${contact.id}:${localDate(new Date(contact.nextFollowUpAt))}`,"career","reminder","high","Follow-up due",`Follow up with ${contact.name}${contact.nextTalkPrep?`: ${contact.nextTalkPrep}`:"."}`,"/career/network"));if(contact.birthday){const md=contact.birthday.slice(5),todayMd=today.slice(5);if(md===todayMd)out.push(C(`career:birthday:${contact.id}:${today.slice(0,4)}`,"career","celebration","normal",`Happy birthday, ${contact.name}!`,`Send ${contact.name} your wishes today.`,"/career/network"))}}
 for(const app of s.career.applications??[]){const age=daysFrom(app.appliedAt,now);if(app.stage==="applied"&&age>=14)out.push(C(`career:application-followup:${app.id}:${Math.floor(age/7)}`,"career","reminder","high","Application follow-up",`${app.role} has had no stage update for ${age} days.`,"/career/jobs"));if(["applied","phone-screen","tech-interview","onsite"].includes(app.stage)&&age>=21)out.push(C(`career:ghost:${app.id}:${Math.floor(age/7)}`,"career","alert","normal","Application may be stalled",`${app.role} has been open for ${age} days. Follow up or update its stage.`,"/career/jobs"))}
 for(const skill of s.career.skills??[])if(skill.lastUsedAt&&now-skill.lastUsedAt>=90*DAY)out.push(C(`career:skill-decay:${skill.id}:${Math.floor(now/(30*DAY))}`,"career","alert","normal","Skill decay warning",`${skill.name} has not been used in ${Math.floor((now-skill.lastUsedAt)/DAY)} days.`,"/career/skills"));
 // Forge — project/task health, deadlines, budgets and aging.
 for(const p of s.forge.projects??[]){if(["blocked","off-track"].includes(p.status))out.push(C(`forge:health:${p.id}:${p.status}`,"projects","alert","high","Project health alert",`${p.title} is ${p.status.toUpperCase()}. Review blockers and dependencies.`,(`/projects/p/${p.id}`)));if(p.deadline&&!p.archived&&!['done','dead'].includes(p.status)){const d=daysUntil(p.deadline,now);if(d<0)out.push(C(`forge:overdue:${p.id}:${today}`,"projects","alert","high","Project overdue",`${p.title} is ${Math.abs(d)} days overdue.`,(`/projects/p/${p.id}`)));else if(d<=7)out.push(C(`forge:deadline:${p.id}:${p.deadline}`,"projects","reminder","high","Deadline approaching",`${p.title} is due in ${d} days.`,(`/projects/p/${p.id}`)))}if(p.budget?.estimated>0&&p.budget.actual/p.budget.estimated>=.8){const ratio=p.budget.actual/p.budget.estimated;out.push(C(`forge:budget:${p.id}:${ratio>=1?"over":"80"}`,"projects","alert",ratio>=1?"critical":"high",ratio>=1?"Project over budget":"Budget threshold reached",`${p.title}: ${Math.round(ratio*100)}% of budget spent.`,(`/projects/p/${p.id}`)))}}
 for(const t of s.forge.tasks??[]){const done=t.completedAt||t.doneAt;if(done)continue;if(t.dueDate){const d=daysUntil(t.dueDate,now);if(d<0)out.push(C(`forge:task-overdue:${t.id}:${today}`,"projects","alert","high","Task overdue",`${t.title} is ${Math.abs(d)} days overdue.`,"/projects/quarry"));else if(d===0)out.push(C(`forge:task-today:${t.id}:${today}`,"projects","reminder","normal","Task due today",t.title,"/projects/quarry"))}if(t.stuck)out.push(C(`forge:task-stuck:${t.id}`,"projects","alert","high","Task is stuck",`${t.title}${t.stuckNote?`: ${t.stuckNote}`:""}`,"/projects/quarry"));if(t.createdAt&&daysFrom(t.createdAt,now)>=21)out.push(C(`forge:task-aging:${t.id}:${Math.floor(now/(7*DAY))}`,"projects","alert","normal","Aging task",`${t.title} has been open for ${daysFrom(t.createdAt,now)} days.`,"/projects/quarry"))}
 // Health — meals, hydration, caffeine, sleep debt and sustained stress.
 const meals=(s.health.meals??[]).filter((x:any)=>x.date===today),water=(s.health.water??[]).filter((x:any)=>x.date===today),waterMl=water.reduce((n:number,x:any)=>n+(x.ml??0),0),caffeine=water.reduce((n:number,x:any)=>n+(x.caffeineMg??0),0);if(hour>=10&&!meals.some((x:any)=>x.slot==="breakfast"))out.push(C(`health:breakfast:${today}`,"health","reminder","normal","Breakfast check","Breakfast is not logged. Eat and record it when you can.","/health/nutrition"));if(hour>=14&&!meals.some((x:any)=>x.slot==="lunch"))out.push(C(`health:lunch:${today}`,"health","reminder","normal","Lunch check","Lunch is not logged yet.","/health/nutrition"));if(hour>=22&&!meals.some((x:any)=>x.slot==="dinner"))out.push(C(`health:dinner:${today}`,"health","reminder","normal","Dinner check","Dinner is not logged yet.","/health/nutrition"));if(hour>=10&&waterMl<500)out.push(C(`health:hydration:${today}:${Math.floor(hour/2)}`,"health","reminder","normal","Hydration reminder",`Only ${waterMl} ml is logged today. Take a water break.`,"/health/hydration"));if(caffeine>400)out.push(C(`health:caffeine:${today}`,"health","alert","high","Caffeine limit exceeded",`${caffeine} mg logged today. Consider stopping caffeine for better sleep.`,"/health/hydration"));
 const sleep=(s.health.sleep??[]).slice().sort((a:any,b:any)=>String(b.date).localeCompare(String(a.date))).slice(0,7),ideal=s.health.profile?.idealSleepHours??8,debt=sleep.reduce((n:number,x:any)=>{const h=Number(x.durationHours)||((x.bedTime&&x.wakeTime)?(new Date(x.wakeTime).getTime()-new Date(x.bedTime).getTime())/3_600_000:0);return n+Math.min(0,h-ideal)},0);if(debt<=-5)out.push(C(`health:sleep-debt:${today}`,"health","alert","high","Sleep debt alert",`Recent sleep debt is about ${Math.abs(debt).toFixed(1)} hours. Prioritize recovery tonight.`,"/health/sleep"));const mind=(s.health.mind??[]).slice().sort((a:any,b:any)=>String(b.date).localeCompare(String(a.date))).slice(0,3);if(mind.length===3&&mind.every((x:any)=>x.stress>=7))out.push(C(`health:stress:${today}`,"health","alert","critical","Sustained high stress","Stress has been high for three check-ins. Reduce load and consider support.","/health/mind"));
 // Entertainment — releases, continuity, unrated completions, backlog and social loans.
 for(const i of s.entertainment.items??[]){if(i.archived)continue;if(i.releaseDate===today||i.scheduledFor===today)out.push(C(`ent:release:${i.id}:${today}`,"entertainment","reminder","normal",i.releaseDate===today?"Available today":"Planned for today",i.title,"/entertainment"));if(i.status==="in-progress"&&now-i.updatedAt>=3*DAY)out.push(C(`ent:continue:${i.id}:${Math.floor(now/(3*DAY))}`,"entertainment","reminder","low",i.type==="book"||i.type==="manga"||i.type==="comic"?"Continue reading":"Continue watching",`${i.title} has been inactive for ${Math.floor((now-i.updatedAt)/DAY)} days.`,"/entertainment"));if(i.status==="completed"&&!i.rating&&i.completedAt&&daysFrom(i.completedAt,now)>=1)out.push(C(`ent:rating:${i.id}`,"entertainment","reminder","normal","Rating reminder",`Rate ${i.title} while it is still fresh.`,"/entertainment"));if(i.status==="planned"&&now-i.createdAt>=30*DAY)out.push(C(`ent:backlog:${i.id}:${Math.floor(now/(30*DAY))}`,"entertainment","reminder","low","Backlog aging",`${i.title} has waited ${Math.floor((now-i.createdAt)/DAY)} days. Start it or clean the queue.`,"/entertainment"))}
 const planned=(s.entertainment.items??[]).filter((i:any)=>i.status==="planned"&&!i.archived);if(planned.length>50)out.push(C(`ent:queue-size:${Math.floor(planned.length/10)}`,"entertainment","alert","normal","Backlog cleanup",`Your Plan-to queue has ${planned.length} titles.`,"/entertainment"));if(!planned.length)out.push(C(`ent:empty-queue:${today}`,"entertainment","progress","low","Your queue is empty","Discover something new when you are ready.","/entertainment"));for(const r of s.entertainment.recommendations??[])if(now-r.createdAt>=14*DAY)out.push(C(`ent:friend-rec:${r.id}`,"entertainment","reminder","low","Friend recommendation waiting","A recommendation from your social circle is still waiting.","/entertainment"));for(const l of s.entertainment.loans??[])if(!l.returnedAt&&daysFrom(l.loanedAt,now)>=30)out.push(C(`ent:loan:${l.id}:${Math.floor(now/(7*DAY))}`,"entertainment","reminder","normal","Borrowed item reminder",`${l.direction==="lent"?"Check on":"Return"} ${s.entertainment.items?.find((i:any)=>i.id===l.itemId)?.title??"the item"} ${l.direction==="lent"?`with ${l.person}`:`to ${l.person}`}.`,"/entertainment"));
 // Global evening pulse.
 if(hour>=20){const sessions=(s.workout.sessions??[]).filter((x:any)=>x.date===today&&x.endedAt).length,doneTasks=(s.tasks??[]).filter((x:any)=>x.completed&&localDate(new Date(x.createdAt))===today).length,media=(s.entertainment.items??[]).filter((x:any)=>x.completedAt===today).length;out.push(C(`system:daily-pulse:${today}`,"system","digest","low","Daily pulse",`${sessions} workout${sessions===1?"":"s"}, ${meals.length} meal logs, ${doneTasks} completed tasks, ${media} media completions.`))}
 return out}
